Use test root disposable for ClassesFqNamesTest
Before this change, running all tests in incremental-compilation-impl
resulted in ClassesFqNamesTest failing with exceptions, one of which
was:

com.intellij.util.IncorrectOperationException: Sorry but parent: com.intellij.core.CoreApplicationEnvironment$1@4b18f96d has already been disposed (see the cause for stacktrace) so the child: com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher@5eb5b521 will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:59)